### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by NearHuscarl** [NearHuscarl/smack#1]
* [ ] Thêm đẩy thông báo khi nhận tn mới lúc ở ngoài app
* [ ] Thêm emoij

@RanChiVo 
* [ ] Thêm reset username vs password
* [ ] Thêm avatar cho người dùng
   * https://stackoverflow.com/questions/29670135/recyclerview-lag-in-scroll
* [ ] Login thông qua gmail, facebook, github
* [ ] Sửa chữ tin nhắn textbox chạm mũi tên xanh
